---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, warning=F, echo=F, include=F}
library(tidyverse)
library(gridExtra)
library(cowplot)
datos = read.csv("base_trabajo_segmentacion.csv", sep=";") 
datos = datos[!duplicated(datos$nit),]
```

```{r}
# Funcion para crear una nueva columna con el porcentaje de las transacciones que ese cliente genera 
calcularTotalPorFilas <- function(df, regexColumnas, nombreColumnaTotal, nombreColumnaPorcentajes)
{
  dataFrameConTotalYPorcentajes <- df %>% mutate(
                                              ColumnaTotal = rowSums(select(.,contains(regexColumnas))),
                                              ColumnaPorcentajes= ColumnaTotal/sum(ColumnaTotal)*100
                                          ) 
  colnames(dataFrameConTotalYPorcentajes)[which(names(dataFrameConTotalYPorcentajes) == "ColumnaTotal")] <- 
    nombreColumnaTotal
  colnames(dataFrameConTotalYPorcentajes)[which(names(dataFrameConTotalYPorcentajes) == "ColumnaPorcentajes")] <- 
    nombreColumnaPorcentajes
                                          
  return(dataFrameConTotalYPorcentajes)
}
```


```{r}
# Calcular los porcentajes para cada tipo de ticket
datosConPorcentajesYTotales <-  datos %>% 
  calcularTotalPorFilas("en_vm", "total_tickets_de_entrada_cliente", "porcentaje_de_tickets_de_entrada_cliente") %>%
  calcularTotalPorFilas("en_tx", "total_transacciones_de_entrada_cliente", "porcentaje_transacciones_de_entrada_cliente") %>%
  calcularTotalPorFilas("sal_vm", "total_tickets_de_salida_cliente", "porcentaje_tickets_de_salida_cliente") %>% 
  calcularTotalPorFilas("sal_tx", "total_transacciones_de_salida_cliente", "porcentaje_transacciones_de_salida_cliente") 
```

# Analisis de los clientes con mas tickets de entrada 

```{r}
# Genera un dataFrame donde compara el top 80% con el resto 
resumenVariableCategoricaComparada <- function(dfMayoria, dfMinoria, columna)
{
    resumenDeMayoria <- dfMayoria %>%
      count(.dots=columna) %>%
      mutate(n = n/sum(n) * 100)
    
    resumenDeMinoria <- dfMinoria %>%
      count(.dots=columna) %>%
      mutate(n = n/sum(n) * 100)
    
    resumenComparativo <- resumenDeMayoria %>% inner_join(resumenDeMinoria, by= structure(names=columna, .Data=columna))
    return(resumenComparativo)
}
```



```{r}
# Se sacan los 300 mejores clientes que es la cantidad que genera el 80% de las transacciones
clientesQueGeneranLaMayoriaTicketsEntrada <- datosConPorcentajesYTotales %>%
                               filter(total_tickets_de_entrada_cliente != 0)  %>%  
                               arrange(desc(total_tickets_de_entrada_cliente)) %>%
                               head(n=300)
clientesQueGeneranMenorTicketsEntrada <- datosConPorcentajesYTotales %>%
                               filter(total_tickets_de_entrada_cliente != 0)  %>%  
                               arrange(desc(total_tickets_de_entrada_cliente)) %>%
                               slice(301: n())
```






```{r}

ImpoCVMayoria <- clientesQueGeneranLaMayoriaTicketsEntrada %>%
  count(impo_cv, sort = TRUE) %>%
  mutate(n = n/sum(n) * 100)

ImpoCVMinoria <- clientesQueGeneranMenorTicketsEntrada %>%
  count(impo_cv, sort = TRUE) %>%
  mutate(n = n/sum(n) * 100)

```


```{r}
# Grafica los datos de una columna seleccionada
graficar_datos <- function (df, columnaDf, nombreMasLegible)
{
  titulo <- sprintf("Porcentaje de %s para cada subgrupo", nombreMasLegible)
  etiquetaMayoria <- sprintf("%s mayoria", nombreMasLegible)
  etiquetaMinoria <- sprintf("%s minoria", nombreMasLegible)
  datos <- reshape2::melt(df, id.vars=columnaDf)
  grafico <- ggplot(data=datos, aes(x=.data[[columnaDf]], y=value, fill=variable)) +
          geom_bar(stat="identity", position="stack") + 
          scale_fill_discrete(name = nombreMasLegible, labels = c(etiquetaMayoria, etiquetaMinoria)) +
          labs(title=titulo, x=nombreMasLegible, y="Porcentaje") + 
          theme(legend.position = "top")
  return(grafico) 
  
}

```


```{r}
# Se escogen nombres que sean mas entendibles para el que lee el reporte
nombresLegibles <- c("Importaciones categorizadas", "Exportaciones categorizadas",
                     "Cuentas por pagar", "Cuentas por cobrar",
                     "Valor de inventarios", "Ventas fisicas", 
                     "Ventas electronicas", "Rotacion de inventarios",
                     "Rotacion de cuentas de pagar", "Rotacion de cuentas por cobrar",
                     "Ciclo de negocio", "Ciclo financiero"
                     )
names(nombresLegibles) <- c("impo_cv", "expo_vt", 
                            "cxp", "cxc", 
                            "totalinventory", "tiene_ventas_fisicas",
                            "tiene_ventas_electronicas", "rotacion_inventarios",
                            "rotacion_cxc", "rotacion_cxp", 
                            "ciclo_negocio", "ciclo_financiero"
                            )
```


```{r fig.ncol=2, fig.align='center', out.height='25%'}
# Se compara el comportamiento de los clientes que generan el 80% con el resto

for (columna in names(nombresLegibles))
{
  datosColumna <- resumenVariableCategoricaComparada(clientesQueGeneranLaMayoriaTicketsEntrada, 
                                     clientesQueGeneranMenorTicketsEntrada, columna)
  grafico <- graficar_datos(datosColumna, columna, nombresLegibles[[columna]])
  print(grafico)
}

```

# Analisis clientes con mas transacciones de entrada mensuales 

```{r}
# Los mejores 80 clientes generan el 80% de las transacciones 
clientesConMasTransaccionesEntrada <- datosConPorcentajesYTotales %>%
                               filter(total_transacciones_de_entrada_cliente != 0)  %>%  
                               arrange(desc(total_transacciones_de_entrada_cliente)) %>%
                               head(n=80)
clintesConMenosTransaccionesEntrada <- datosConPorcentajesYTotales %>%
                                filter(total_transacciones_de_entrada_cliente != 0)  %>%  
                               arrange(desc(total_transacciones_de_entrada_cliente)) %>%
                               slice(81: n())
```


```{r}
# Se grafica las variables categoricas comparadas en ambos grupos
for (columna in names(nombresLegibles))
{
  datosColumna <- resumenVariableCategoricaComparada(clientesConMasTransaccionesEntrada, 
                                     clintesConMenosTransaccionesEntrada, columna)
  grafico <- graficar_datos(datosColumna, columna, nombresLegibles[[columna]])
  print(grafico)
}
```

# Analisis clientes con mas tickets de salida

```{r}
# Con 500 clientes se genera el 80% de tickets de salida
clientesQueGeneranLaMayoriaTicketsSalida <- datosConPorcentajesYTotales %>%
                               filter(total_tickets_de_salida_cliente != 0)  %>%  
                               arrange(desc(total_tickets_de_salida_cliente)) %>%
                               head(n=500)

clientesQueGeneranMenorTicketsSalida <- datosConPorcentajesYTotales %>%
                               filter(total_tickets_de_salida_cliente != 0)  %>%  
                               arrange(desc(total_tickets_de_salida_cliente)) %>%
                               slice(501: n())
```


```{r}
# Compara las variables categoricas
for (columna in names(nombresLegibles))
{
  datosColumna <- resumenVariableCategoricaComparada(clientesQueGeneranLaMayoriaTicketsSalida, 
                                     clientesQueGeneranMenorTicketsSalida, columna)
  grafico <- graficar_datos(datosColumna, columna, nombresLegibles[[columna]])
  print(grafico)
}
```


# Clientes con mas transacciones mensuales de salida 

```{r}
# Los mejores 400 clientes generan el 80% de las transacciones
clientesQueGeneranLaMayoriaTicketsSalida <- datosConPorcentajesYTotales %>%
                               filter(total_transacciones_de_salida_cliente != 0)  %>%  
                               arrange(desc(total_transacciones_de_salida_cliente)) %>%
                               head(n=400)

clientesQueGeneranMenorTicketsSalida <- datosConPorcentajesYTotales %>%
                               filter(total_transacciones_de_salida_cliente != 0)  %>%  
                               arrange(desc(total_transacciones_de_salida_cliente)) %>%
                               slice(401: n())
```


```{r}
# Grafica las variables categoricas comparadas en los dos subgrupos 
for (columna in names(nombresLegibles))
{
  datosColumna <- resumenVariableCategoricaComparada(clientesQueGeneranLaMayoriaTicketsSalida, 
                                     clientesQueGeneranMenorTicketsSalida, columna)
  grafico <- graficar_datos(datosColumna, columna, nombresLegibles[[columna]])
  print(grafico)
}
```

